export const WECHAT_MALL_ACTIVITIES = [
    {
      title: '加价换购',
      color: '#84aac6',
      key: '1070',
      right: 15,
      bottom: 0,
    },
    {
      title: '折扣',
      color: '#84aac6',
      key: '2020',
      right: 5,
      bottom: 0,
    },
    {
      title: '特价菜',
      color: '#84aac6',
      key: '1010',
      right: 5,
      bottom: 0,
    },
    {
      title: '团购活动',
      color: '#84aac6',
      key: '4010',
      right: 5,
      bottom: 0,
    },
    {
      title: '第二份打折',
      color: '#84aac6',
      key: '1050',
      right: 5,
      bottom: 0,
    },
    {
      title: '特价菜',
      color: '#84aac6',
      key: '1010',
      right: 5,
      bottom: 0,
    },
    {
      title: '菜品推荐',
      color: '#84aac6',
      key: '5010',
      right: 5,
      bottom: 0,
    },
    {
      title: '加价升级换新',
      color: '#84aac6',
      key: '1090',
      right: 5,
      bottom: 0,
    },
    {
      title: '满减/每满减',
      color: '#84aac6',
      key: '2010',
      right: 5,
      bottom: 0,
    },
    {
      title: '随机立减',
      color: '#84aac6',
      key: '2030',
      right: 5,
      bottom: 0,
    },
    {
      title: '满赠/每满赠',
      color: '#84aac6',
      key: '1030',
      right: 5,
      bottom: 0,
    },
    {
      title: '买赠',
      color: '#84aac6',
      key: '1020',
      right: 5,
      bottom: 0,
    },
    {
      title: '买三免一',
      color: '#84aac6',
      key: '1060',
      right: 5,
      bottom: 0,
    },
    {
      title: '买减/买折',
      color: '#84aac6',
      key: '2040',
      right: 5,
      bottom: 0,
    },
    {
      title: '组合减免/折扣',
      color: '#84aac6',
      key: '2050',
      right: 5,
      bottom: 0,
    },
    {
      title: '搭赠',
      color: '#84aac6',
      key: '1040',
      right: 5,
      bottom: 0,
    },
    {
      title: '低价促销',
      color: '#84aac6',
      key: '2080',
      right: 5,
      bottom: 0,
    },
    {
      title: '累计次数赠送',
      color: '#84aac6',
      key: '1080',
      right: 5,
      bottom: 0,
    },
    {
      title: '累计次数减免',
      color: '#84aac6',
      key: '2070',
      right: 5,
      bottom: 0,
    },
    {
      title: '称重买赠',
      color: '#84aac6',
      key: '1021',
      right: 5,
      bottom: 0,
    },
  ];
  